apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataentryapi-deployment
spec:
  selector:
    matchLabels:
      app: datanetryapi-pod
  template:
    metadata:
      labels:
        app: dataentryapi-pod
    spec:
      containers:
      - name: dataentryapi-container
        image: dataentryapi.azurecr.io/dataentryapi:dev
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
